/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 magic.gltf 
Author: MAR.COS. (https://sketchfab.com/mar.cos.)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-magic-compass-4f935b708d194be5b8a51369756c5caa
Title: Stylized Magic Compass
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/magic.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-3, -17, 12]} rotation={[-Math.PI / 2, 0, 0]} scale={400}>
          <mesh geometry={nodes.cop023_low_M_Compass_0.geometry} material={materials.M_Compass} />
          <mesh geometry={nodes.cop023_low_M_Glass_0.geometry} material={materials.M_Glass} />
          <mesh geometry={nodes.cop023_low_M_Crystale_0.geometry} material={materials.M_Crystale} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/magic.gltf')
